// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZbKwSC_ZwELzrCFlfu--R1pDlwCyDko',
    appId: '1:248394168950:web:947501118e1abcd23a7d57',
    messagingSenderId: '248394168950',
    projectId: 'teaching-app-556c7',
    authDomain: 'teaching-app-556c7.firebaseapp.com',
    storageBucket: 'teaching-app-556c7.firebasestorage.app',
    measurementId: 'G-NEE3N97K6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Ro6VQdnIVaVnnWB7Eh4VMnsf92EHXag',
    appId: '1:248394168950:android:666af340b812797c3a7d57',
    messagingSenderId: '248394168950',
    projectId: 'teaching-app-556c7',
    storageBucket: 'teaching-app-556c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoUalmypkXUQuj360sPYaNn9G9fCVhAXk',
    appId: '1:248394168950:ios:9287b95cbe9838e03a7d57',
    messagingSenderId: '248394168950',
    projectId: 'teaching-app-556c7',
    storageBucket: 'teaching-app-556c7.firebasestorage.app',
    iosBundleId: 'com.example.teachingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoUalmypkXUQuj360sPYaNn9G9fCVhAXk',
    appId: '1:248394168950:ios:9287b95cbe9838e03a7d57',
    messagingSenderId: '248394168950',
    projectId: 'teaching-app-556c7',
    storageBucket: 'teaching-app-556c7.firebasestorage.app',
    iosBundleId: 'com.example.teachingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHZbKwSC_ZwELzrCFlfu--R1pDlwCyDko',
    appId: '1:248394168950:web:7b84a2721f59d30a3a7d57',
    messagingSenderId: '248394168950',
    projectId: 'teaching-app-556c7',
    authDomain: 'teaching-app-556c7.firebaseapp.com',
    storageBucket: 'teaching-app-556c7.firebasestorage.app',
    measurementId: 'G-VB17W7WC21',
  );
}
